#! /usr/bin/env python3
# Dark Sky Doc: https://darksky.net/dev
# Make an api call
import json, requests
def set_up_api_call(lat, long):
    #url vars
    api_token = 'YOUR_API_TOKEN_HERE'
    url = 'https://api.darksky.net/forecast/'+api_token+'/'+lat+','+long'

    # call data
    data = requests.get(url).json()
    #print(data)
    return data

def read_out_api_data(data):
    #parse data
    current = data['currently']
    summary = current['summary']
    temp = current['temperature']
    wind = current['windSpeed']
    uv = current['uvIndex']

    min_cast = data['minutely']['data'][0]
    min_sum = data['minutely']['summary']
    #precipType = min_cast['precipType']

    daily = data['daily']['data'][0]
    moon = daily['moonPhase']

    #loop through data
    weather_forecast = [summary, temp, wind, uv, min_sum, moon]

    #for x in weather_forecast:
	#print(x)



    print(min_sum)
    print('The temp is ' + str(temp))
    print('The wind is blowing at ' + str(wind))
    print('UV index is at ' + str(uv))
    print('The moon is at ' + str(moon))

# run program
lat = int(input('what lat'))
lon = int(input('what lon'))
data = set_up_api_call(lat, long)
read_out_api_data(data)
